### article like
POST http://localhost:8080/api/v1/like/f50bec20-7de6-46c1-92d2-3941849f33b5
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTgwOTI3MTYsImlkIjo1MSwicm9sZSI6IlJPTEVfTU9ERVJBVE9SIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsImV4cCI6MTcxODE3OTExNiwiaXNzIjoiS3VuVXpUZXN0In0.nObe1hm4MhkTuskMbg8RsraSN4PexPHqfpfcgWvYV3rRcE9FOLXQC0-rH7ZgNzFwwX6Evn6QHi3rdfdBvJaUyw


### article like dislike
GET http://localhost:8080/api/v1/dislike/abad63e2-1b4b-4178-bb32-39080d6f5c8c
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTgwOTI3MTYsImlkIjo1MSwicm9sZSI6IlJPTEVfTU9ERVJBVE9SIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsImV4cCI6MTcxODE3OTExNiwiaXNzIjoiS3VuVXpUZXN0In0.nObe1hm4MhkTuskMbg8RsraSN4PexPHqfpfcgWvYV3rRcE9FOLXQC0-rH7ZgNzFwwX6Evn6QHi3rdfdBvJaUyw


### article like delete
DELETE http://localhost:8080/api/v1/delete/f50bec20-7de6-46c1-92d2-3941849f33b5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc4NTExMDQsImlkIjo1MSwicm9sZSI6IlJPTEVfTU9ERVJBVE9SIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsImV4cCI6MTcxNzkzNzUwNCwiaXNzIjoiS3VuVXpUZXN0In0.3fWzEz9qiOYWIDCnQ--BIDEEiHPtEixw_RaLeQp1-Erk2Fr2wuZ9zw4GfUHW7Zq6L_0pluS_vp96bE08LxIV2A
