### Registration with Phone
POST localhost:8080/auth/registration
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTczNDY4NTUsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsImV4cCI6MTcxNzQzMzI1NSwiaXNzIjoiS3VuVXpUZXN0In0.D8wxzFyMsHJWhW5DlkO4m-98yvbOEwnhZW5nDiiuoiEl1-H2H8eNI3q30ypmacruDBXBfTLRYdkcNMDQcL4DAQ

{
  "name": "Jek",
  "surname": "Lashara",
  "email": "hojiakbarandaqulov5@gmail.com",
  "password": "1234",
  "role": "ROLE_ADMIN"
}

###
#POST  localhost:8080/auth/registration
#Content-Type: application/json
#Authorization: Basic YWRtaW46YWRtaW5qb24=
#
#{
#  "name": "Java",
#  "surname": "Developer",
#  "phone": "998995092376",
#  "password": "1234",
#  "role": "ROLE_ADMIN"
#}
###
GET http://localhost:8080/auth/verification/15
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTczNDY4NTUsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsImV4cCI6MTcxNzQzMzI1NSwiaXNzIjoiS3VuVXpUZXN0In0.D8wxzFyMsHJWhW5DlkO4m-98yvbOEwnhZW5nDiiuoiEl1-H2H8eNI3q30ypmacruDBXBfTLRYdkcNMDQcL4DAQ


### Login
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "hojiakbarandaqulov5@gmail.com",
  "password": "1234"
}

###
#### Login
#POST localhost:8080/auth/login
#Content-Type: application/json
#Authorization: Basic YWRtaW46YWRtaW5qb24=
#
#{
#  "email": "",
#  "password": "1234"
#}
### resend in registration
GET localhost:8080/auth/sms/998995092376
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTcyNTkzNzEsInJvbGUiOiJST0xFX1VTRVIiLCJ1c2VybmFtZSI6ImFsaXNoQGdtYWlsLmNvbSIsImV4cCI6MTcxNzM0NTc3MSwiaXNzIjoiS3VuVXpUZXN0In0.gJf6M-JR2sJOPkunHxewks_83lvZGENTseHwOFvTway1UXUT3FN7KzNHlSCp5x1pEH0k-D9ZiHPLebEJtwduZA

{
  "mobile_phone": "998999476970",
  "message": "This is test from Eskiz",
  "from": "4546"
}

###
GET localhost:8080/auth/registration/resend/hojiakbarandaqulov5@gmail.com
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTcyNTkzNzEsInJvbGUiOiJST0xFX1VTRVIiLCJ1c2VybmFtZSI6ImFsaXNoQGdtYWlsLmNvbSIsImV4cCI6MTcxNzM0NTc3MSwiaXNzIjoiS3VuVXpUZXN0In0.gJf6M-JR2sJOPkunHxewks_83lvZGENTseHwOFvTway1UXUT3FN7KzNHlSCp5x1pEH0k-D9ZiHPLebEJtwduZA



