### Post Region to example server
POST localhost:8080//category/created
Content-Type: application/json
#

{
  "orderNumber": 4,
  "nameUz": "AUDIO",
  "nameRu": "АУДИО",
  "nameEn": "AUDIO"
}

### Put Region example server
PUT localhost:8080/category/update/4
Content-Type: application/json

{
  "orderNumber": 4,
  "nameUz": "AUDIO",
  "nameRu": "АУДИО",
  "nameEn": "AUDIO"
}
### Delete Region example server
DELETE localhost:8080/category/delete/4

### Get all Region example server
GET localhost:8080/category/RegionAll

### GetByLanguage example server
GET localhost:8080/category/GetByLanguage/nameEn
