### Post Region to example server
POST localhost:8080//category/create
Content-Type: application/json

{
  "orderNumber": 8,
  "nameUz": "AUDIO",
  "nameRu": "АУДИО",
  "nameEn": "AUDIO"
}

### Put Region example server
PUT localhost:8080/category/update/12
Content-Type: application/json

{
  "orderNumber": 4,
  "nameUz": "Audio",
  "nameRu": "АУДИО",
  "nameEn": "AUDIO"
}
### Delete Region example server
DELETE localhost:8080/category/delete/12

### Get all Region example server
GET localhost:8080/category/all

### GetByLanguage example server
GET localhost:8080/category/lang
