### GET request to example server
GET localhost:8080/email/history/hojiakbarandaqulov5@gmail.com


### GET request to example server
GET localhost:8080/email/by/12@gmail.com

### getByEmail
GET http://localhost:8080/email/by/hojiakbarandaqulov5@gmail.com

### Pagination
GET http://localhost:8080/email/pagination?page=1&size=4