### Post Region to example server
POST http://localhost:8080/region/adm/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTczMzMzMDMsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsImV4cCI6MTcxNzQxOTcwMywiaXNzIjoiS3VuVXpUZXN0In0.o5FnrTeXfqPc3abGUya3EoRCNLWEXPoSC0hREh6dP0bgsh7ybqWzWd8VmSTZxXMJao2Ap2mokyC9H2OcyFgK7w

#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTcwNTg3MDAsImlkIjoxMSwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcxNzE0NTEwMCwiaXNzIjoiS3VuVXpUZXN0In0.39wJspZogiu1l02zJNiENCrTSzM1SwnWsRsCo9dFwLpSRaokPVO25PveCmoLLd41e_Axmjj3n1LwE9NrjkOl3Q

{
  "orderNumber": 0,
  "nameUz": "Jizzax",
  "nameRu": "Djizzax",
  "nameEn": "Jizzakh"
}
### Put Region example server
PUT localhost:8080/region/adm/update/23
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTczMzMzMDMsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsImV4cCI6MTcxNzQxOTcwMywiaXNzIjoiS3VuVXpUZXN0In0.o5FnrTeXfqPc3abGUya3EoRCNLWEXPoSC0hREh6dP0bgsh7ybqWzWd8VmSTZxXMJao2Ap2mokyC9H2OcyFgK7w

#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTcwNTg3MDAsImlkIjoxMSwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcxNzE0NTEwMCwiaXNzIjoiS3VuVXpUZXN0In0.39wJspZogiu1l02zJNiENCrTSzM1SwnWsRsCo9dFwLpSRaokPVO25PveCmoLLd41e_Axmjj3n1LwE9NrjkOl3Q

{
  "orderNumber": 4,
  "nameUz": "Samarqand",
  "nameRu": "Самарканд",
  "nameEn": "Samarkand"
}
### Delete Region example server
DELETE localhost:8080/region/adm/delete/23
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTczMzMzMDMsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsImV4cCI6MTcxNzQxOTcwMywiaXNzIjoiS3VuVXpUZXN0In0.o5FnrTeXfqPc3abGUya3EoRCNLWEXPoSC0hREh6dP0bgsh7ybqWzWd8VmSTZxXMJao2Ap2mokyC9H2OcyFgK7w

#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTcwNTg3MDAsImlkIjoxMSwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcxNzE0NTEwMCwiaXNzIjoiS3VuVXpUZXN0In0.39wJspZogiu1l02zJNiENCrTSzM1SwnWsRsCo9dFwLpSRaokPVO25PveCmoLLd41e_Axmjj3n1LwE9NrjkOl3Q

### Get all Region example server
GET localhost:8080/region/adm/regionAll
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTczMzMzMDMsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsImV4cCI6MTcxNzQxOTcwMywiaXNzIjoiS3VuVXpUZXN0In0.o5FnrTeXfqPc3abGUya3EoRCNLWEXPoSC0hREh6dP0bgsh7ybqWzWd8VmSTZxXMJao2Ap2mokyC9H2OcyFgK7w

#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTcwNTg3MDAsImlkIjoxMSwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcxNzE0NTEwMCwiaXNzIjoiS3VuVXpUZXN0In0.39wJspZogiu1l02zJNiENCrTSzM1SwnWsRsCo9dFwLpSRaokPVO25PveCmoLLd41e_Axmjj3n1LwE9NrjkOl3Q

### GetByLanguage example server
GET localhost:8080/region/lang
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTczMzMzMDMsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsImV4cCI6MTcxNzQxOTcwMywiaXNzIjoiS3VuVXpUZXN0In0.o5FnrTeXfqPc3abGUya3EoRCNLWEXPoSC0hREh6dP0bgsh7ybqWzWd8VmSTZxXMJao2Ap2mokyC9H2OcyFgK7w

