### Post Region to example server
POST http://localhost:8080/region/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTY5MDk1NDQsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE3MTY5OTU5NDQsImlzcyI6Ikt1blV6VGVzdCJ9.vJS4-nqegy-mGNIWN-sV_DB5RkmK2PP0J12dgGXLLhW3-Wp5eTjDhH1WqKUF54AlYcUmDpSr2CwQd6hCyj6Y8w

{
  "orderNumber": 0,
  "nameUz": "Jizzax",
  "nameRu": "Djizzax",
  "nameEn": "Jizzakh"
}

### Put Region example server
PUT localhost:8080/region/update/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTcwMzIzNDQsImlkIjo3LCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzE3MTE4NzQ0LCJpc3MiOiJLdW5VelRlc3QifQ.OKS7JsH8uWdMgms6KEmAyxZWIHWicJrrstDFodzs4jPUR7nlvz41Nj55NrrTaE71BpuuCdOmcyjSdxtQ3o7dcA

{
  "orderNumber": 4,
  "nameUz": "Samarqand",
  "nameRu": "Самарканд",
  "nameEn": "Samarkand"
}
### Delete Region example server
DELETE localhost:8080/region/delete/7
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTcwMzIzNDQsImlkIjo3LCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzE3MTE4NzQ0LCJpc3MiOiJLdW5VelRlc3QifQ.OKS7JsH8uWdMgms6KEmAyxZWIHWicJrrstDFodzs4jPUR7nlvz41Nj55NrrTaE71BpuuCdOmcyjSdxtQ3o7dcA

### Get all Region example server
GET localhost:8080/region/regionAll

### GetByLanguage example server
GET localhost:8080/region/lang
