### Post Type to example server
POST localhost:8080//types/adm/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTczMzMzMDMsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsImV4cCI6MTcxNzQxOTcwMywiaXNzIjoiS3VuVXpUZXN0In0.o5FnrTeXfqPc3abGUya3EoRCNLWEXPoSC0hREh6dP0bgsh7ybqWzWd8VmSTZxXMJao2Ap2mokyC9H2OcyFgK7w

#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTcwNTg3MDAsImlkIjoxMSwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcxNzE0NTEwMCwiaXNzIjoiS3VuVXpUZXN0In0.39wJspZogiu1l02zJNiENCrTSzM1SwnWsRsCo9dFwLpSRaokPVO25PveCmoLLd41e_Axmjj3n1LwE9NrjkOl3Q

{
  "orderNumber": 5,
  "nameUz": "Energetika ",
  "nameRu": "Первый шаг к реформе энергетики был?",
  "nameEn": "The first step towards energy reform was"
}
### Put Type example server
PUT localhost:8080/types/adm/update/18
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTczMzMzMDMsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsImV4cCI6MTcxNzQxOTcwMywiaXNzIjoiS3VuVXpUZXN0In0.o5FnrTeXfqPc3abGUya3EoRCNLWEXPoSC0hREh6dP0bgsh7ybqWzWd8VmSTZxXMJao2Ap2mokyC9H2OcyFgK7w

#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTcwNTg3MDAsImlkIjoxMSwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcxNzE0NTEwMCwiaXNzIjoiS3VuVXpUZXN0In0.39wJspZogiu1l02zJNiENCrTSzM1SwnWsRsCo9dFwLpSRaokPVO25PveCmoLLd41e_Axmjj3n1LwE9NrjkOl3Q

{
  "order_number": 1,
  "name_uz": "Энергетика ",
  "name_ru": "Первый шаг к реформе энергетики был сделан?",
  "name_en": "The first step towards energy reform was taken?"
}
### Delete Type example server
DELETE localhost:8080/types/adm/delete/18
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTczMzMzMDMsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsImV4cCI6MTcxNzQxOTcwMywiaXNzIjoiS3VuVXpUZXN0In0.o5FnrTeXfqPc3abGUya3EoRCNLWEXPoSC0hREh6dP0bgsh7ybqWzWd8VmSTZxXMJao2Ap2mokyC9H2OcyFgK7w

#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTcwNTg3MDAsImlkIjoxMSwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcxNzE0NTEwMCwiaXNzIjoiS3VuVXpUZXN0In0.39wJspZogiu1l02zJNiENCrTSzM1SwnWsRsCo9dFwLpSRaokPVO25PveCmoLLd41e_Axmjj3n1LwE9NrjkOl3Q

### Get all Type example server
GET localhost:8080/types/adm/typeAllPagination?page=1&size=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTczMzMzMDMsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsImV4cCI6MTcxNzQxOTcwMywiaXNzIjoiS3VuVXpUZXN0In0.o5FnrTeXfqPc3abGUya3EoRCNLWEXPoSC0hREh6dP0bgsh7ybqWzWd8VmSTZxXMJao2Ap2mokyC9H2OcyFgK7w

#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTcwNTg3MDAsImlkIjoxMSwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcxNzE0NTEwMCwiaXNzIjoiS3VuVXpUZXN0In0.39wJspZogiu1l02zJNiENCrTSzM1SwnWsRsCo9dFwLpSRaokPVO25PveCmoLLd41e_Axmjj3n1LwE9NrjkOl3Q

### GetByLanguage example server
GET localhost:8080/types/language
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTczMzMzMDMsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsImV4cCI6MTcxNzQxOTcwMywiaXNzIjoiS3VuVXpUZXN0In0.o5FnrTeXfqPc3abGUya3EoRCNLWEXPoSC0hREh6dP0bgsh7ybqWzWd8VmSTZxXMJao2Ap2mokyC9H2OcyFgK7w

#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTcwNTg3MDAsImlkIjoxMSwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcxNzE0NTEwMCwiaXNzIjoiS3VuVXpUZXN0In0.39wJspZogiu1l02zJNiENCrTSzM1SwnWsRsCo9dFwLpSRaokPVO25PveCmoLLd41e_Axmjj3n1LwE9NrjkOl3Q
