### Post Type to example server
POST localhost:8080//types/create
Content-Type: application/json

{
  "orderNumber": 4,
  "nameUz": "Energetika ",
  "nameRu": "Первый шаг к реформе энергетики был сделан?",
  "nameEn": "The first step towards energy reform was taken?"
}
### Put Type example server
PUT localhost:8080/types/update/1
Content-Type: application/json

{
  "order_number": 1,
  "name_uz": "Энергетика ",
  "name_ru": "Первый шаг к реформе энергетики был сделан?",
  "name_en": "The first step towards energy reform was taken?"
}
### Delete Type example server
DELETE localhost:8080/types/delete/5

### Get all Type example server
GET localhost:8080/types/typeAllPagination?page=1&size=3

### GetByLanguage example server
GET localhost:8080/types/language
